Models/EnvVariables.cs
namespace BuggyAppService.Models
{
    public class EnvVariables
    {
        public string? Key { get; set; }
        public string? Value { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace BuggyAppService.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/HighCPU.cs
namespace BuggyAppService.Models
{
    public class HighCPU
    {
        public string? Name { get; set; }
        public string? Email { get; set; }
    }
}

Controllers/HomeController.cs
using BuggyAppService.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BuggyAppService.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();

        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/StackOverflowController.cs
using Microsoft.AspNetCore.Mvc;

namespace BuggyAppService.Controllers
{
    public class StackOverflowController : Controller
    {
        public IActionResult Index()
        {

            return View();
        }

        public IActionResult Index2()
        {

            RecursiveMethod();

            return View();
        }
        private void RecursiveMethod()
        {

            for (int i = 0; i < 1500; i++)
            {
                RecursiveMethod();
            }

        }
    }
}

Views/AppDomainUnload/Index.cshtml
@{
    ViewData["Title"] = "App Domain Unload";
}

<script type="text/javascript">
    function GetTimeZoneOffset() {

        var dot = ".";
       
    }

</script>
<h1>App Domain Unload</h1>
<p> Click on button below to create a file localy in web.config </p>
@*<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <asp:Button runat="server" id="btnCreateFile" Text="CreateFile" OnClick="btnCreateFile_click" />
</asp:Content>*@

@*asp-action="btnCreateFile_click"*@

<p> This will trigger app domain unload due to FCN mode</p> </>
<h1></h1>
<p>you can set the in the web.config FCNmode='disabled' as workaround </p> </>
<h1></h1>

<a href="@Url.Action("Index","AppDomainUnload", new {id="x=createFile" })"
   class="btn btn-primary btn-lg">Create File </a>

<h3>Request status: @ViewData["RequestStatus"]</h3>

Views/ClientCertAuth/Index.cshtml
@{
    ViewData["Title"] = "ClientCertAuth";
}
<script type="text/javascript">
       
</script>

<h1>Client Certificate Authentication</h1>
<p>Select a certificate and paste URL in the text box</p>

<form method="post" enctype="multipart/form-data" asp-controller="ClientCertAuth" asp-action="Index">
    <div class="mb-3">
        <label for="formFile" class="form-label">Select certificate (*.pfx)</label>
        <input class="form-control" type="file" id="formFile" name="postedFile">
    </div>
     
    <label for="formFile" class="form-label">Certificate password:</label>
    <input class="form-control" type="password" placeholder="Certificate password:" aria-label="password" name="certpass">
    <br />

    <label for="formFile" class="form-label">Endpoint URL:</label>
    <input class="form-control" type="text" placeholder="Paste URL here:" aria-label="Path to PFX:" name="url">
    <br />

    <button type="submit" class="btn btn-primary mb-3">Send request</button>
    <br/>
    
    <br />
    <span>@Html.Raw(ViewBag.Message)</span>
</form>


<h3>Request status: @ViewData["RequestStatus"]</h3>

Views/EnvVariables/Index.cshtml
@model List<BuggyAppService.Models.EnvVariables>;
@using Markdig;
@{
    ViewData["Title"] = "Env Variables";
}

<h1>Environment Variables</h1>
<h1></h1>
@*@ViewData["EnvVariables"]*@
<div>
   
    @*@Markdown.Parse(@ViewData["EnvVariables"].ToString())*@
    @Markdown.ToHtml(@ViewData["EnvVariables"].ToString())
</div>


<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>

                <th>Key</th>
                <th>Value</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var envKey in Model)
            {
                <tr>
                    <td>@envKey.Key</td>
                    <td>@envKey.Value</td>
                </tr>
            }
        </tbody>
    </table>
</div>

@*<asp:GridView ID="GridView1" class="table table-bordered table-condensed table-responsive table-hover " runat="server" AutoGenerateColumns="false">
    <Columns>

        <asp:BoundField DataField="Key" HeaderText="Key" />
        <asp:BoundField DataField="Value" HeaderText="Value" />
    </Columns>
</asp:GridView>*@

Views/HighCPU/Index.cshtml
@model BuggyAppService.Models.HighCPU
@{
    ViewData["Title"] = "High CPU";
}

<h1>High CPU</h1>
<h1>Time Taken:</h1>
<h1>@ViewData["TimeTaken"]</h1>

<p>You can click the high cpu button to reproduce high CPU </p>

<a href="@Url.Action("Index","HighCPU",new {id="concat" })" class="btn btn-primary btn-lg">HighCPU Concatenating String </a>




@*<div class="myform">
    <h1 class="display-4">High CPU using regex</h1>

    <form asp-action="Index" method="post">
        <div class="myforma">
            <label for="exampleFormControlInput" class="form-label">Enter String for Regex mathc</label>
            <input type="text" class="form-control" asp-for="Name" id="exampleFormControlInput" placeholder="ReproForHighCPU">
           @* @Html.TextBoxFor(m => m.Name)

        </div>
        <div>
            <p></p>
            <button type="submit">Submit form</button>
            <p></p>
        </div>

    </form>
</div>*@



<p>You can check the troubleshooting steps to find out the root cause for high CPU</p>

<a href="@Url.Action("HighCPU","Troubleshooting")" class="btn btn-primary btn-lg">How to Troubleshoot High CPU </a>

Views/SNAT/Index.cshtml
@model BuggyAppService.Models.HighCPU
@{
    ViewData["Title"] = "Snat Port Exhaustion";
}

<h1>SNAT port exhaustion</h1>
<h2>@ViewData["PageContent"]</h2>
<a href="@Url.Action("Index","SNAT",new {id="execute"})" class="btn btn-primary btn-lg">Make request </a>


<p>You can check the troubleshooting steps to find out the root cause for SNAT port exhaustion</p>

<a href="@Url.Action("SNAT","Troubleshooting")" class="btn btn-primary btn-lg">How to Troubleshoot SNAT port Exhaustion </a>



<p> After adding the key for the slow outbound request you can use Azure Load Testing or a linux vm to make a load test using :</p>
<p> ab -r -n 5000 -c 500 -s 120 https://buggyappservice.azurewebsites.net/SNAT/Index/execute</p>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BuggyAppService</title>
   
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BuggyAppService.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BuggyAppService</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="StackOverflow" asp-action="Index">Crash</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HighCPU" asp-action="Index">High CPU</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HighMemory" asp-action="Index">High Memory</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="_500Exception" asp-action="Index">500 Exception</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SlowPage" asp-action="Index">Slow Page</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SNAT" asp-action="Index">SNAT Port Exhaustion</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="StartUpIssue" asp-action="Index">StartUpIssue</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HealthCheck" asp-action="Index">Health Check</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AppDomainUnload" asp-action="Index">AppDomainUnload</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="EnvVariables" asp-action="Index">Env Variables</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UpcomingFeatures" asp-action="Index">Upcoming Features</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ClientCertAuth" asp-action="Index">Client Certificate Authentication</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ConvertPDF" asp-action="Index">Convert PDF</a>
                        </li>
                        <li>
                            <div class="btn-group">
                                <button type="button" class="btn btn-success dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                    Troubleshooting Steps
                                </button>
                                <ul class="dropdown-menu">
                                    <li> <a class="nav-link text-dark" asp-area="" asp-controller="Troubleshooting" asp-action="Error">500 error</a></li>
                                    <li> <a class="nav-link text-dark" asp-area="" asp-controller="Troubleshooting" asp-action="Crash">Crash</a></li>
                                    <li> <a class="nav-link text-dark" asp-area="" asp-controller="Troubleshooting" asp-action="SlowRequest">Slow Request</a></li>
                                    <li> <a class="nav-link text-dark" asp-area="" asp-controller="Troubleshooting" asp-action="HighCPU">High CPU</a></li>
                                    <li> <a class="nav-link text-dark" asp-area="" asp-controller="Troubleshooting" asp-action="SNAT">Snat Port Exhaustion</a></li>
                                    <li> <a class="nav-link text-dark" asp-area="" asp-controller="Troubleshooting" asp-action="HighMemory">High Memory</a></li>
                       @*              <li><a class="dropdown-item" href="#">Action</a></li>
                                    <li><a class="dropdown-item" href="#">Another action</a></li>
                                    <li><a class="dropdown-item" href="#">Something else here</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" href="#">Separated link</a></li> *@
                                </ul>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BuggyAppService - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/StackOverflow/Index.cshtml
@{
    ViewData["Title"] = "Crash";
}

<h1>Crash</h1>

<p>You can click the Crash button to reproduce a stack overflow </p>
<a href="@Url.Action("Index2","StackOverflow")" class="btn btn-primary btn-lg">Crash - stack overflow </a>


<p>You can check the troubleshooting steps to find out the root cause for crash</p>

<a href="@Url.Action("Crash","Troubleshooting")" class="btn btn-primary btn-lg">How to troubleshoot Crash </a>

Views/StartUpIssue/Index.cshtml
@{
    ViewData["Title"] = "Start Up Issue";
}
<script type="text/javascript">
    function GetTimeZoneOffset() {

        var dot = ".";

    }

</script>
<h1>Start Up Issue</h1>
@* <p> you can set the app settings key "StartupIssue" = true in order to reproduce a startup issue</p>
<p> You can enable ASPNETCORE_DETAILEDERRORS=true in app service configuration/app settings to enable detailed error in the page </p> </>
<h1></h1>
<p>you can set the app settings key "StartupIssue" = coldStart60  or "StartupIssue" = coldStart240</p>
<p>  in order to reproduce a cold start issue (it will take 2min to fail with 500.37) </p>
<p>HTTP Error 500.37 - ASP.NET Core app failed to start within startup time limit</p>
<h1></h1> *@


<div class="accordion" id="accordionExample">
    <div class="accordion-item">
        <h2 class="accordion-header">
            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                Startup Error
            </button>
        </h2>
        <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                Set the app settings key  <strong> "StartupIssue" = true. </strong> in order to reproduce a startup error
                <p></p>
                <img src="~/images/startupError.png" class="img-fluid">
            </div>
        </div>
    </div>
    <div class="accordion-item">
        <h2 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                Cold Start
            </button>
        </h2>
        <div id="collapseTwo" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                <p>   set the app settings key  <strong> "StartupIssue" = coldStart60 </strong> to reproduce a cold start of 60 sec </p> 
                <p>   set the app settings key  <strong> "StartupIssue" = coldStart240 </strong> to reproduce a cold start of 240 sec </p>
               
            </div>
        </div>
    </div>
    <div class="accordion-item">
        <h2 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                Enable Detailed Errors
            </button>
        </h2>
        <div id="collapseThree" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                Enable   <strong> ASPNETCORE_DETAILEDERRORS=true</strong> in app service configuration/app settings to enable detailed error in the page
            </div>
        </div>
    </div>
</div>

Views/Troubleshooting/Crash.cshtml
@{
    ViewData["Title"] = "Crash";
}
<script type="text/javascript">
    function GetTimeZoneOffset() {

        var dot = ".";
       
    }

</script>


<h1>Crash</h1>


<div class="accordion" id="accordionExample">
    <div class="accordion-item">
        <h2 class="accordion-header">
            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                Crash detector
            </button>
        </h2>
        <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                <h3> Verify if they process is crashing using Application Crashes detector </h3>
                <img src="~/images/CrashDetector.png" class="img-fluid">
            </div>
        </div>
    </div>
    <div class="accordion-item">
        <h2 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                Collect Memory dump using Crash Monitoring feature
            </button>
        </h2>
        <div id="collapseTwo" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                <h3> Enable Crash Monitoring to collect a memory dump o crash</h3>
                <img src="~/images/CrashMonitoring.png" class="img-fluid">
            </div>
        </div>
    </div>
    <div class="accordion-item">
        <h2 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                Memory dump analysis
            </button>
        </h2>
        <div id="collapseThree" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                <br /> A crash dump will open on the context of the thread that caused the crash. This case, thread 32.
                <br /> <img src="~/images/DA_Crash_01.png" class="img-fluid">
                <br /> First thing we always check in the dump is the CLR version and establish if we are in a supported scenario.
                <br /> <img src="~/images/DumpAnalysisLmvmCoreClr.png" class="img-fluid">
                <br /> Looking at the call stack of thread 32:
                <br /> <img src="~/images/DA_Crash_02.png" class="img-fluid">
                <br /> We see the same method called over and over making the stack to overflow.
                <br /> Checking code we can see the recursive call that filled the stack.

                <br /> <img src="~/images/DA_Crash_03.png" class="img-fluid">

            </div>
        </div>
    </div>
</div>

Views/Troubleshooting/HealthCheck.cshtml
@{
    ViewData["Title"] = "Health Check";
}
<script type="text/javascript">
    function GetTimeZoneOffset() {

        var dot = ".";
       
    }

</script>
<h1>Slow Request</h1>
<p> Troubleshootiing guide for Slow Request </p>
<p></p>
<p> Set the key  HealthCheckIssue=true and the health check path to /HealthCheck to induce a 500 erorr for the health check </p>

<div class="accordion" id="accordionExample">
    <div class="accordion-item">
        <h2 class="accordion-header">
            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                Slow request execution detector 
            </button>
        </h2>
        <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                <h3> Check the "Slow request execution detector" to find more details about the slowness </h3>
                <img src="~/images/DetectorSlowRequestExecution.png" class="img-fluid">
            </div>
        </div>
    </div>
    <div class="accordion-item">
        <h2 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                Check Application Insights 
            </button>
        </h2>
        <div id="collapseTwo" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                <h3> Check application insights to find more details about the slowness </h3>
                <img src="~/images/AppInsightsSlowness.png" class="img-fluid">
                <h3> Drill into samples </h3>
                <img src="~/images/AppInsightsDrillSlowness.png" class="img-fluid">
                <p> If we don't see any slow dependency, that means the time is spent inside the code </p>
            </div>
        </div>
    </div>
    <div class="accordion-item">
        <h2 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                Collect Profiler Trace 
            </button>
        </h2>
        <div id="collapseThree" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                <h3> If the issue is reproducible on demand you can Collect profiler trace :  </h3>
                <img src="~/images/Profiler.png" class="img-fluid">
                <p>Or you can use auto heal to collect profiler trace or memory dump by creating a rule for slowness </p>
            </div>
        </div>
    </div>
    <div class="accordion-item">
        <h2 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                Collect Memory Dump
            </button>
        </h2>
        <div id="collapseFour" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                <h3> Use AutoHeal to collect Memory Dump or Profiler Trace  </h3>
                <img src="~/images/AuthHealSlowness.png" class="img-fluid">
                <p>Or you can use auto heal to collect profiler trace or memory dump by creating a rule for slowness </p>
            </div>
        </div>

    </div>
    <div class="accordion-item">
        <h2 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
                Memory Dump Analysis
            </button>
        </h2>
        <div id="collapseFive" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                <p>Once we have collected the memory dump using SlowPage scenario </p>
                <p> https://buggyappservice.azurewebsites.net/SlowPage/Index/time=40000  </p>
                <p> Open Memory dump in WinDbg</p>
                
                <p>First thing we always check in the dump is the CLR version and establish if we are in a supported scenario.</p>
                <p>lmvm clr       .net framework</p>
                <p>lmvm coreclr   .net core</p>
                <img src="~/images/DumpAnalysisLmvmCoreClr.png" class="img-fluid">
                <p>Checking running requests:</p>
                <p>!aspxcorepages -n -a</p>
                <img src="~/images/DumpAnalysisAspxcorepages.png" class="img-fluid">
                <br />
                <p>!ck2</p>
                <img src="~/images/DumpAnalysisCK2.png" class="img-fluid">
                <br />
                <p>!decompilemember BuggyAppService!BuggyAppService.Controllers.SlowPage.Index</p>
                <img src="~/images/DumpAnalysisDecompileSlowPage.png" class="img-fluid">
                <br />
                <p>We can see that thread 34 stack, specifically BuggyAppService!BuggyAppService.Controllers.SlowPage.Index calls Thread.Sleep().</p>
            </div>
        </div>
    </div>
</div>

Views/Troubleshooting/HighCPU.cshtml
@{
    ViewData["Title"] = "High CPU";
}
<script type="text/javascript">
    function GetTimeZoneOffset() {

        var dot = ".";
       
    }

</script>
<h1>High CPU</h1>


<div class="accordion" id="accordionExample">
    <div class="accordion-item">
        <h2 class="accordion-header">
            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                CPU Drill Down detector
            </button>
        </h2>
        <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                <h3> Verify the process that consumes high CPU : use CPU drill down detector </h3>
                <img src="~/images/CPUDrillDown.png" class="img-fluid">
            </div>
        </div>
    </div>
    <div class="accordion-item">
        <h2 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                Collect Memory dump using Proactive CPU Monitoring
            </button>
        </h2>
        <div id="collapseTwo" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                <h3> Enable Proactive CPU Monitoring to collect a memory dump o crash</h3>
                <img src="~/images/ProactiveCPUMonitoring.png" class="img-fluid">
            </div>
        </div>
    </div>
    <div class="accordion-item">
        <h2 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                Memory dump analysis
            </button>
        </h2>
        <div id="collapseThree" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
            <div class="accordion-body">
                <br /> First thing we always check in the dump is the CLR version and establish if we are in a supported scenario.
                <br /> <img src="~/images/DA_HighCPU_01.png" class="img-fluid">
                <br /> Show thread pool status (threads running or not) + CPU usage. That is CPU usage on entire machine. It's not a must that w3wp.exe is taking all that CPU.
                <br /> <img src="~/images/DA_HighCPU_02.png" class="img-fluid">
                <br /> Looking at threads that are doing work:
                <br /> <img src="~/images/DA_HighCPU_03.png" class="img-fluid">
                <br /> Seems like all threads that are doing work are doing file operations, except threads 51. Let's have a closer look:
                <br /> <img src="~/images/DA_HighCPU_04.png" class="img-fluid">
                <br /> String concatenation, expensive operation CPU wise. Looking at the code:
                <br /> <img src="~/images/DA_HighCPU_05.png" class="img-fluid">

            </div>
        </div>
    </div>
</div>

Views/Troubleshooting/Index.cshtml
@{
    ViewData["Title"] = "Start Up Issue";
}
<script type="text/javascript">
    function GetTimeZoneOffset() {

        var dot = ".";
       
    }

</script>
<h1>Start Up Issue</h1>
<p> you can set the app settings key "StartupIssue" = true in order to reproduce a startup issue</p>
<p> You can enable ASPNETCORE_DETAILEDERRORS=true in app service configuration/app settings to enable detailed error in the page </p> </>
<h1></h1>
<p>you can set the app settings key "StartupIssue" = coldStart60  or "StartupIssue" = coldStart240</p>
<p>  in order to reproduce a cold start issue (it will take 2min to fail with 500.37) </p> 
<p>HTTP Error 500.37 - ASP.NET Core app failed to start within startup time limit</p>
<h1></h1>